create table public.skills (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id),
  name text not null,
  category text not null check (category in ('plumbing','tutoring','hair','sewing','repairs','other')),
  town text not null,
  description text not null,
  services text[] not null default '{}',
  phone_number text not null,
  status text not null check (status in ('active','withdrawn')) default 'active',
  created_at timestamptz not null default now()
);

alter table public.skills enable row level security;

create policy "anyone can read active skills"
on public.skills
for select
to anon, authenticated
using (status = 'active');

create policy "owners can read their own skills"
on public.skills
for select
to authenticated
using (auth.uid() = owner_id);

create policy "authenticated users can insert their own skill"
on public.skills
for insert
to authenticated
with check (auth.uid() = owner_id);

create index on public.skills (owner_id);
create policy "owners can update their own skill"
on public.skills
for update
to authenticated
using (auth.uid() = owner_id)
with check (auth.uid() = owner_id);
